root: data
train_hdfs:
- clotho_dev_cnext.hdf
val_hdfs:
- clotho_val_cnext.hdf
test_hdfs:
- clotho_eval_cnext.hdf
predict_hdfs:
- clotho_dcase_aac_analysis_cnext.hdf
- clotho_dcase_aac_test_cnext.hdf
train_batch_keys:
- frame_embs
- frame_embs_shape
- captions
- keywords
val_batch_keys:
- frame_embs
- frame_embs_shape
- dataset
- subset
- fname
- mult_captions
- mult_references
- keywords
test_batch_keys:
- frame_embs
- frame_embs_shape
- dataset
- subset
- fname
- mult_captions
- mult_references
- keywords
predict_batch_keys:
- frame_embs
- frame_embs_shape
- dataset
- subset
- fname
- keywords
batch_size: 64
num_workers: 12
pin_memory: true
train_drop_last: false
verbose: 1
